import type { Metadata } from 'next';
import { ChartColumn } from 'lucide-react';

import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

import { Providers } from './providers';

import { Button } from '@/components/ui/button';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Code Stats',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        inter.variable,
      )}
    >
      <body className='min-h-full flex flex-col'>
        <Providers>
          <header className='p-4 bg-secondary-foreground text-white'>
            <h1 className='flex items-center gap-1'>
              <ChartColumn className='h-7 w-7 text-primary animate-text-gradient' />
              <span>Code Stats</span>
              <Button className='p-4 bg-secondary-foreground ml-auto border-2 border-accent font-normal hover:bg-(--accent-muted)'>
                About
              </Button>
            </h1>
          </header>
          {children}
          <footer className='mt-auto border-t px-4'>{new Date().getFullYear()}</footer>
        </Providers>
      </body>
    </html>
  );
}
